PREFIX ns1: <https://model.ccmm.cz/vocabulary/datacite#>
PREFIX ns2: <https://model.ccmm.cz/vocabulary/ccmm#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ns3: <http://www.w3.org/ns/adms#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX ns4: <http://www.w3.org/ns/locn#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT (?v2 AS ?local_identifier) (?v3 AS ?award_title) (?v4 AS ?funding_program) (?v7 AS ?funder_identifier_value) (?v9 AS ?funder_identifier_scheme_label) (?v10 AS ?funder_identifier_authorized) (?v11 AS ?funder_name) (?v12 AS ?funder_alternate_name) (?v14 AS ?funder_contact_point_data_box) (?v15 AS ?funder_contact_point_email) (?v16 AS ?funder_contact_point_phone) (?v18 AS ?funder_contact_point_address_label) (?v19 AS ?funder_contact_point_address_full_address) (?v20 AS ?funder_contact_point_address_po_box) (?v21 AS ?funder_contact_point_address_thoroughfare) (?v22 AS ?funder_contact_point_address_locator_designator) (?v23 AS ?funder_contact_point_address_locator_name) (?v24 AS ?funder_contact_point_address_address_area) (?v25 AS ?funder_contact_point_address_post_name) (?v26 AS ?funder_contact_point_address_administrative_unit_level_1) (?v27 AS ?funder_contact_point_address_administrative_unit_level_2) (?v28 AS ?funder_contact_point_address_post_code)
WHERE {
  ?v1 a ns1:FundingReference .
  OPTIONAL {
    ?v1 ns1:awardNumber ?v2 .
  }
  OPTIONAL {
    ?v1 ns1:awardTitle ?v3 .
  }
  OPTIONAL {
    ?v1 ns2:fundingProgram ?v4 .
  }
  ?v5 a foaf:Agent .
  OPTIONAL {
    ?v6 a ns3:Identifier .
    ?v6 skos:notation ?v7 .
    ?v8 a ns2:IdentifierScheme .
    OPTIONAL {
      ?v8 rdfs:label ?v9 .
    }
    ?v6 ns2:inScheme ?v8 .
    OPTIONAL {
      ?v6 ns2:authorized ?v10 .
    }
    ?v5 ns2:hasIdentifier ?v6 .
  }
  ?v5 foaf:name ?v11 .
  OPTIONAL {
    ?v5 vcard:organization-name ?v12 .
  }
  OPTIONAL {
    ?v13 a ns2:ContactDetails .
    OPTIONAL {
      ?v13 ns2:dataBox ?v14 .
    }
    OPTIONAL {
      ?v13 ns2:email ?v15 .
    }
    OPTIONAL {
      ?v13 ns2:phone ?v16 .
    }
    OPTIONAL {
      ?v17 a ns4:Address .
      OPTIONAL {
        ?v17 rdfs:label ?v18 .
      }
      OPTIONAL {
        ?v17 ns4:fullAddress ?v19 .
      }
      OPTIONAL {
        ?v17 ns4:poBox ?v20 .
      }
      OPTIONAL {
        ?v17 ns4:thoroughfare ?v21 .
      }
      OPTIONAL {
        ?v17 ns4:locatorDesignator ?v22 .
      }
      OPTIONAL {
        ?v17 ns4:locatorName ?v23 .
      }
      OPTIONAL {
        ?v17 ns4:addressArea ?v24 .
      }
      OPTIONAL {
        ?v17 ns4:postName ?v25 .
      }
      OPTIONAL {
        ?v17 ns4:adminUnitL1 ?v26 .
      }
      OPTIONAL {
        ?v17 ns4:adminUnitL2 ?v27 .
      }
      OPTIONAL {
        ?v17 ns4:postCode ?v28 .
      }
      ?v13 vcard:hasAddress ?v17 .
    }
    ?v5 dcat:contactPoint ?v13 .
  }
  ?v1 ns1:hasFunderIdentifier ?v5 .
}
